### ISSUE TITLE
Different session ID on settings and actual element

### ISSUE THREAD

**Issue by CrocoDillon** [Boonstra/Slideshow#7]
I have an issue where the session ID on settings is 0 (`var SlideshowPluginSettings_0 = { ... }`), but on the actual element it's 1 (`data-session-id="1"`). This is with only one Slideshow on the page. Result is a JS error (because [`this.settings`](https://github.com/Boonstra/Slideshow/blob/76c39e7665922ec9b9cc5bfec1ef84350053c23b/js/frontend/slideshow/slideshow.constructor.js#L38) is undefined).

I worked around it by removing the [sessionCounter increment](https://github.com/Boonstra/Slideshow/blob/76c39e7665922ec9b9cc5bfec1ef84350053c23b/classes/SlideshowPlugin.php#L107) with the limitation that there can only be one Slideshow per page now.

Any idea where this issue can come from? (Oh yeah, it's version 2.2.21)

**Comment by Boonstra** [comment]
I'm sorry for my late response.

Perhaps the issue is caused by how the assignment of `$sessionID` and the increment of `self::$sessionCounter` are on the same line. I've separated these actions in version 2.2.22, hopefully this will fix your issue without you having to work around it.

**Comment by CrocoDillon** [comment]
Thanks for the reply, better late than never :wink: :+1:
